steps:
  # Build the container image
  - name: "gcr.io/cloud-builders/docker"
    args:
      - "build"
      - "-t"
      - "gcr.io/$PROJECT_ID/landingsiteservice:latest"
      - "."
    id: "Building the container image"

  # Push the container image to Container Registry
  - name: "gcr.io/cloud-builders/docker"
    args:
      - "push"
      - "gcr.io/$PROJECT_ID/landingsiteservice:latest"
    id: "Pushing the image to registry"

  # Deploy container image to Cloud Run
  - name: "gcr.io/cloud-builders/gcloud"
    args:
      - "run"
      - "deploy"
      - "landingsiteservice"
      - "--image"
      - "gcr.io/$PROJECT_ID/landingsiteservice:latest"
      - "--region"
      - "us-central1"
      - "--platform"
      - "managed"
      - "--allow-unauthenticated"
    id: "Deploying the app to cloud run"

options:
  default_logs_bucket_behavior: REGIONAL_USER_OWNED_BUCKET

timeout: 6100s
